In [3]:
import requests

In [4]:
r = requests.get('https://api.github.com/events')

In [5]:
r

In [6]:
r.status_code

200

In [7]:
r.url

'https://api.github.com/events'

In [8]:
r.text

'[{"id":"9343575044","type":"PushEvent","actor":{"id":60653600,"login":"mix113","display_login":"mix113","gravatar_id":"","url":"https://api.github.com/users/mix113","avatar_url":"https://avatars.githubusercontent.com/u/60653600?"},"repo":{"id":1133518622,"name":"mix113/leaders-image","url":"https://api.github.com/repos/mix113/leaders-image"},"payload":{"repository_id":1133518622,"push_id":31637129004,"ref":"refs/heads/main","head":"bec34ef856853d276cf6945c9c80547cf55c496e","before":"17277ccf4be1f4e8699c2ac0b806c895568da950"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575234","type":"PushEvent","actor":{"id":19983904,"login":"lavraicse","display_login":"lavraicse","gravatar_id":"","url":"https://api.github.com/users/lavraicse","avatar_url":"https://avatars.githubusercontent.com/u/19983904?"},"repo":{"id":1180332610,"name":"lavraicse/githubpages-test","url":"https://api.github.com/repos/lavraicse/githubpages-test"},"payload":{"repository_id":1180332610,"push_id":31637129203,"ref":"refs/heads/main","head":"c2a06f59cf733a39d450282972cd5efe23663c82","before":"8653f2b7bc50ddeab773157d433ac73e9615338c"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575043","type":"PushEvent","actor":{"id":123560,"login":"hughperkins","display_login":"hughperkins","gravatar_id":"","url":"https://api.github.com/users/hughperkins","avatar_url":"https://avatars.githubusercontent.com/u/123560?"},"repo":{"id":994002809,"name":"Genesis-Embodied-AI/quadrants","url":"https://api.github.com/repos/Genesis-Embodied-AI/quadrants"},"payload":{"repository_id":994002809,"push_id":31637128988,"ref":"refs/heads/main","head":"450192a14987b8605c51228fd07caf703b8c589d","before":"fa4fa572af98b48287188d1f9221115e86680a62"},"public":true,"created_at":"2026-03-13T00:09:58Z","org":{"id":149333263,"login":"Genesis-Embodied-AI","gravatar_id":"","url":"https://api.github.com/orgs/Genesis-Embodied-AI","avatar_url":"https://avatars.githubusercontent.com/u/149333263?"}},{"id":"9343575326","type":"PushEvent","actor":{"id":111310114,"login":"Anderfg13","display_login":"Anderfg13","gravatar_id":"","url":"https://api.github.com/users/Anderfg13","avatar_url":"https://avatars.githubusercontent.com/u/111310114?"},"repo":{"id":1180271486,"name":"Anderfg13/Lab_P3_BluePrints_React_UI","url":"https://api.github.com/repos/Anderfg13/Lab_P3_BluePrints_React_UI"},"payload":{"repository_id":1180271486,"push_id":31637129230,"ref":"refs/heads/main","head":"8ed3468f0cdc94c74f9b2ccb12cfed567f23a462","before":"4cf7d598957cc1ce85db65518be169503a7106b5"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575307","type":"PushEvent","actor":{"id":163665366,"login":"shabazz007","display_login":"shabazz007","gravatar_id":"","url":"https://api.github.com/users/shabazz007","avatar_url":"https://avatars.githubusercontent.com/u/163665366?"},"repo":{"id":1000700498,"name":"shabazz007/bibfixer","url":"https://api.github.com/repos/shabazz007/bibfixer"},"payload":{"repository_id":1000700498,"push_id":31637129120,"ref":"refs/heads/main","head":"e2793187866bb369f7d4074242c3bd686879341c","before":"1ead1af56f2d972a219df24919511010ad6daa41"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575306","type":"PushEvent","actor":{"id":129240278,"login":"SkyRaks","display_login":"SkyRaks","gravatar_id":"","url":"https://api.github.com/users/SkyRaks","avatar_url":"https://avatars.githubusercontent.com/u/129240278?"},"repo":{"id":1122034243,"name":"SkyRaks/CryptoAggregator","url":"https://api.github.com/repos/SkyRaks/CryptoAggregator"},"payload":{"repository_id":1122034243,"push_id":31637129206,"ref":"refs/heads/main","head":"e00859db729c3b2568d6594e72d18e892bbb93f5","before":"82fbe4e06255436941ddc3c7f4b1cbb9e570d6f5"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575288","type":"PushEvent","actor":{"id":204646541,"login":"Whalica","display_login":"Whalica","gravatar_id":"","url":"https://api.github.com/users/Whalica","avatar_url":"https://avatars.githubusercontent.com/u/204646541?"},"repo":{"id":1174570277,"name":"Whalica/Competitive_Programming_Notes","url":"https://api.github.com/repos/Whalica/Competitive_Programming_Notes"},"payload":{"repository_id":1174570277,"push_id":31637129147,"ref":"refs/heads/main","head":"53a49382efd9cac94d7d9096d606a463edc758fe","before":"5d72021cc65c7f882192ea3b207b7adf2548b9bf"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575286","type":"PushEvent","actor":{"id":5831547,"login":"cooleye","display_login":"cooleye","gravatar_id":"","url":"https://api.github.com/users/cooleye","avatar_url":"https://avatars.githubusercontent.com/u/5831547?"},"repo":{"id":1179980934,"name":"cooleye/private-traffic-system","url":"https://api.github.com/repos/cooleye/private-traffic-system"},"payload":{"repository_id":1179980934,"push_id":31637129271,"ref":"refs/heads/main","head":"1dfba5c12803368bc87483f7dca5bce49d7c0aaf","before":"1e841895bfc368e51a310f0941e9a3bff45d249a"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575281","type":"PushEvent","actor":{"id":198982749,"login":"Copilot","display_login":"copilot-swe-agent","gravatar_id":"","url":"https://api.github.com/users/Copilot","avatar_url":"https://avatars.githubusercontent.com/u/198982749?"},"repo":{"id":520721473,"name":"barbrickdesign/barbrickdesign.github.io","url":"https://api.github.com/repos/barbrickdesign/barbrickdesign.github.io"},"payload":{"repository_id":520721473,"push_id":31637129173,"ref":"refs/heads/copilot/remove-monthly-video-briefings","head":"ec9decf3e71f694cdb8c2bce9d0fc91a1b4636e4","before":"061b560eb4e436a6272e07639aa584dceb5f0deb"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575267","type":"PushEvent","actor":{"id":254231878,"login":"tomohikohorai-source","display_login":"tomohikohorai-source","gravatar_id":"","url":"https://api.github.com/users/tomohikohorai-source","avatar_url":"https://avatars.githubusercontent.com/u/254231878?"},"repo":{"id":1132477041,"name":"tomohikohorai-source/pjn-site","url":"https://api.github.com/repos/tomohikohorai-source/pjn-site"},"payload":{"repository_id":1132477041,"push_id":31637129167,"ref":"refs/heads/main","head":"92f0d32af132bcdcf18e01b8471d48436a55df0c","before":"f352a9d7ef5341d91420b66471576c59dfe0367b"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575252","type":"PushEvent","actor":{"id":1839708,"login":"spali","display_login":"spali","gravatar_id":"","url":"https://api.github.com/users/spali","avatar_url":"https://avatars.githubusercontent.com/u/1839708?"},"repo":{"id":565458011,"name":"spali/esp-idf","url":"https://api.github.com/repos/spali/esp-idf"},"payload":{"repository_id":565458011,"push_id":31637129252,"ref":"refs/heads/release/v5.1.5","head":"d63dfeb1092efd1463fe21ef0acb289e120fde92","before":"cb66fb1e0ba5aa81f8600c4e8010157b09f60ae0"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575247","type":"CreateEvent","actor":{"id":49699333,"login":"dependabot[bot]","display_login":"dependabot","gravatar_id":"","url":"https://api.github.com/users/dependabot[bot]","avatar_url":"https://avatars.githubusercontent.com/u/49699333?"},"repo":{"id":1180331025,"name":"m3g/SFEModelling.jl","url":"https://api.github.com/repos/m3g/SFEModelling.jl"},"payload":{"ref":"dependabot/github_actions/julia-actions/cache-3","ref_type":"branch","full_ref":"refs/heads/dependabot/github_actions/julia-actions/cache-3","master_branch":"main","description":"Supercritical Fluid Extraction data modeling tool","pusher_type":"user"},"public":true,"created_at":"2026-03-13T00:09:58Z","org":{"id":5021636,"login":"m3g","gravatar_id":"","url":"https://api.github.com/orgs/m3g","avatar_url":"https://avatars.githubusercontent.com/u/5021636?"}},{"id":"9343575241","type":"PushEvent","actor":{"id":159125892,"login":"lovable-dev[bot]","display_login":"lovable-dev","gravatar_id":"","url":"https://api.github.com/users/lovable-dev[bot]","avatar_url":"https://avatars.githubusercontent.com/u/159125892?"},"repo":{"id":1180284206,"name":"alwardiabdo50-web/gentle-reader","url":"https://api.github.com/repos/alwardiabdo50-web/gentle-reader"},"payload":{"repository_id":1180284206,"push_id":31637129220,"ref":"refs/heads/main","head":"4e83792ab90422073fb79d8f55de91aa7c03d246","before":"e0223c3195fb84605c5cd915aa6509f6afad0505"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575034","type":"PushEvent","actor":{"id":200283118,"login":"viciosO123","display_login":"viciosO123","gravatar_id":"","url":"https://api.github.com/users/viciosO123","avatar_url":"https://avatars.githubusercontent.com/u/200283118?"},"repo":{"id":1077885341,"name":"viciosO123/muon","url":"https://api.github.com/repos/viciosO123/muon"},"payload":{"repository_id":1077885341,"push_id":31637128925,"ref":"refs/heads/main","head":"76bf44ed9e096cf48ed23c16f1dea7e2d62be090","before":"1ccd44f86955ab0c223ecfdc7c16a1a4b3accc28"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575224","type":"PushEvent","actor":{"id":1839708,"login":"spali","display_login":"spali","gravatar_id":"","url":"https://api.github.com/users/spali","avatar_url":"https://avatars.githubusercontent.com/u/1839708?"},"repo":{"id":565458011,"name":"spali/esp-idf","url":"https://api.github.com/repos/spali/esp-idf"},"payload":{"repository_id":565458011,"push_id":31637129172,"ref":"refs/heads/release/v4.3.3","head":"d7c1b1f01e79f59db6a888994ea4c7448238a02d","before":"933ae3b1f43c8724297e29e0b00e66002f554b1b"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575223","type":"PushEvent","actor":{"id":2250046,"login":"reiver","display_login":"reiver","gravatar_id":"","url":"https://api.github.com/users/reiver","avatar_url":"https://avatars.githubusercontent.com/u/2250046?"},"repo":{"id":1180212882,"name":"reiver/vibefed","url":"https://api.github.com/repos/reiver/vibefed"},"payload":{"repository_id":1180212882,"push_id":31637129123,"ref":"refs/heads/master","head":"179e2065dbc368687629b11a15ba20268a8893ce","before":"aec754ba1b3e2c156f4aca5e880bad1b8d454d77"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575215","type":"PushEvent","actor":{"id":267562634,"login":"simonchangdevote","display_login":"simonchangdevote","gravatar_id":"","url":"https://api.github.com/users/simonchangdevote","avatar_url":"https://avatars.githubusercontent.com/u/267562634?"},"repo":{"id":1179542722,"name":"simonchangdevote/ambassador-platform","url":"https://api.github.com/repos/simonchangdevote/ambassador-platform"},"payload":{"repository_id":1179542722,"push_id":31637129086,"ref":"refs/heads/main","head":"24994d27477c09e94f1d5872d0427011008f0b98","before":"3a5bbc1873057ea09250473bededdb10dc64a54e"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575207","type":"PushEvent","actor":{"id":197130100,"login":"DIPPUSINHA","display_login":"DIPPUSINHA","gravatar_id":"","url":"https://api.github.com/users/DIPPUSINHA","avatar_url":"https://avatars.githubusercontent.com/u/197130100?"},"repo":{"id":926119116,"name":"DIPPUSINHA/Tg-Forwards","url":"https://api.github.com/repos/DIPPUSINHA/Tg-Forwards"},"payload":{"repository_id":926119116,"push_id":31637129082,"ref":"refs/heads/main","head":"0a8d086c9dd03cffca21e8de3cf84aa0a045b50d","before":"a00478cdd29ffdc3a1830d7a9ad69ec4f2879957"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575206","type":"PushEvent","actor":{"id":83982370,"login":"Francis-Calingo","display_login":"Francis-Calingo","gravatar_id":"","url":"https://api.github.com/users/Francis-Calingo","avatar_url":"https://avatars.githubusercontent.com/u/83982370?"},"repo":{"id":838117588,"name":"Francis-Calingo/francis-calingo","url":"https://api.github.com/repos/Francis-Calingo/francis-calingo"},"payload":{"repository_id":838117588,"push_id":31637129115,"ref":"refs/heads/main","head":"3dc9a58f6aeb4c9a780674e866338661149c123d","before":"1f506308e9fcafa65d52c2d4fec1cc8b2f272539"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575202","type":"PushEvent","actor":{"id":166664864,"login":"Dpfastner","display_login":"Dpfastner","gravatar_id":"","url":"https://api.github.com/users/Dpfastner","avatar_url":"https://avatars.githubusercontent.com/u/166664864?"},"repo":{"id":1142080842,"name":"Dpfastner/fantasy-sports-platform","url":"https://api.github.com/repos/Dpfastner/fantasy-sports-platform"},"payload":{"repository_id":1142080842,"push_id":31637129204,"ref":"refs/heads/main","head":"df1ea33369224b0d924e56dbca594c7972cd3f73","before":"65ac474fb41cd1ab45327d3a32de755f116a5a48"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575191","type":"PushEvent","actor":{"id":15665609,"login":"saitama45","display_login":"saitama45","gravatar_id":"","url":"https://api.github.com/users/saitama45","avatar_url":"https://avatars.githubusercontent.com/u/15665609?"},"repo":{"id":1012847804,"name":"saitama45/david","url":"https://api.github.com/repos/saitama45/david"},"payload":{"repository_id":1012847804,"push_id":31637129107,"ref":"refs/heads/master","head":"246f0330ffecc587fea54393592f1e78f3ad2a8e","before":"f67e26fe93851734a2c129eaa33fce07a9e83a56"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575183","type":"DeleteEvent","actor":{"id":8371576,"login":"srbryers","display_login":"srbryers","gravatar_id":"","url":"https://api.github.com/users/srbryers","avatar_url":"https://avatars.githubusercontent.com/u/8371576?"},"repo":{"id":1162898953,"name":"srbryers/slope","url":"https://api.github.com/repos/srbryers/slope"},"payload":{"ref":"v1.25.2","ref_type":"tag","full_ref":"refs/tags/v1.25.2","pusher_type":"user"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575182","type":"PushEvent","actor":{"id":49736102,"login":"kodiakhq[bot]","display_login":"kodiakhq","gravatar_id":"","url":"https://api.github.com/users/kodiakhq[bot]","avatar_url":"https://avatars.githubusercontent.com/u/49736102?"},"repo":{"id":170304778,"name":"ItinerisLtd/iroots","url":"https://api.github.com/repos/ItinerisLtd/iroots"},"payload":{"repository_id":170304778,"push_id":31637129098,"ref":"refs/heads/master","head":"c5d2f55b8fc9c836a434bd0bd2a3aa2de77cf7b4","before":"b7fc0d4a631e4f8cc16fbf013cd9c51a2f298297"},"public":true,"created_at":"2026-03-13T00:09:58Z","org":{"id":32365928,"login":"ItinerisLtd","gravatar_id":"","url":"https://api.github.com/orgs/ItinerisLtd","avatar_url":"https://avatars.githubusercontent.com/u/32365928?"}},{"id":"9343575178","type":"PushEvent","actor":{"id":178097291,"login":"ppl-committer","display_login":"ppl-committer","gravatar_id":"","url":"https://api.github.com/users/ppl-committer","avatar_url":"https://avatars.githubusercontent.com/u/178097291?"},"repo":{"id":834941258,"name":"pewpewlive/ppl-data","url":"https://api.github.com/repos/pewpewlive/ppl-data"},"payload":{"repository_id":834941258,"push_id":31637129080,"ref":"refs/heads/master","head":"c61cd1fa299071635e389143ddf5f14706fa280e","before":"6c12cd2f1d95196b8ed737c462dd08fa2cd38fce"},"public":true,"created_at":"2026-03-13T00:09:58Z","org":{"id":109729559,"login":"pewpewlive","gravatar_id":"","url":"https://api.github.com/orgs/pewpewlive","avatar_url":"https://avatars.githubusercontent.com/u/109729559?"}},{"id":"9343575175","type":"PushEvent","actor":{"id":28951336,"login":"Spikewmu","display_login":"Spikewmu","gravatar_id":"","url":"https://api.github.com/users/Spikewmu","avatar_url":"https://avatars.githubusercontent.com/u/28951336?"},"repo":{"id":1159670668,"name":"Spikewmu/n8n-workflow-backups2026","url":"https://api.github.com/repos/Spikewmu/n8n-workflow-backups2026"},"payload":{"repository_id":1159670668,"push_id":31637129113,"ref":"refs/heads/main","head":"1bc8188ff5b8120fe396dca50fdfa0266d227e2e","before":"9abe387ed77d04b652f2be7911484a921d1ca330"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575161","type":"PushEvent","actor":{"id":1839708,"login":"spali","display_login":"spali","gravatar_id":"","url":"https://api.github.com/users/spali","avatar_url":"https://avatars.githubusercontent.com/u/1839708?"},"repo":{"id":565458011,"name":"spali/esp-idf","url":"https://api.github.com/repos/spali/esp-idf"},"payload":{"repository_id":565458011,"push_id":31637129095,"ref":"refs/heads/release/v4.4.2","head":"deccae0fc09d581feca0feb48dd93d9b71cebedc","before":"0215c97ba8498eac4a5b548f6f0265e9c5a61089"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575158","type":"PushEvent","actor":{"id":153868092,"login":"KaykyOne","display_login":"KaykyOne","gravatar_id":"","url":"https://api.github.com/users/KaykyOne","avatar_url":"https://avatars.githubusercontent.com/u/153868092?"},"repo":{"id":1126369143,"name":"KaykyOne/novus-cfc","url":"https://api.github.com/repos/KaykyOne/novus-cfc"},"payload":{"repository_id":1126369143,"push_id":31637129045,"ref":"refs/heads/dev","head":"957bbc85ad4f0caa790437da35288dacd21db461","before":"0b50820636ea6402845dd27716257dd1d3e886d1"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575153","type":"PushEvent","actor":{"id":41898282,"login":"github-actions[bot]","display_login":"github-actions","gravatar_id":"","url":"https://api.github.com/users/github-actions[bot]","avatar_url":"https://avatars.githubusercontent.com/u/41898282?"},"repo":{"id":741524414,"name":"hey-api/openapi-ts","url":"https://api.github.com/repos/hey-api/openapi-ts"},"payload":{"repository_id":741524414,"push_id":31637129039,"ref":"refs/heads/main","head":"e88abc67656064aa7de338e781f0970b1f316ca3","before":"7fe03ab5e3e74febe1a546d412eef72e745000aa"},"public":true,"created_at":"2026-03-13T00:09:58Z","org":{"id":164436240,"login":"hey-api","gravatar_id":"","url":"https://api.github.com/orgs/hey-api","avatar_url":"https://avatars.githubusercontent.com/u/164436240?"}},{"id":"9343575152","type":"PushEvent","actor":{"id":267099388,"login":"michelleryvus-cpu","display_login":"michelleryvus-cpu","gravatar_id":"","url":"https://api.github.com/users/michelleryvus-cpu","avatar_url":"https://avatars.githubusercontent.com/u/267099388?"},"repo":{"id":1178060416,"name":"michelleryvus-cpu/Evernote_Migrate","url":"https://api.github.com/repos/michelleryvus-cpu/Evernote_Migrate"},"payload":{"repository_id":1178060416,"push_id":31637129053,"ref":"refs/heads/main","head":"c937ef0464dd2e8a5e24a8172dd170802e4efbf9","before":"1f187c9f14daf19375b4bbdbfc1f2d4cd368f73f"},"public":true,"created_at":"2026-03-13T00:09:58Z"},{"id":"9343575151","type":"DeleteEvent","actor":{"id":92490720,"login":"Alxit0","display_login":"Alxit0","gravatar_id":"","url":"https://api.github.com/users/Alxit0","avatar_url":"https://avatars.githubusercontent.com/u/92490720?"},"repo":{"id":1072435618,"name":"Taca-Ua/taca-ua-app","url":"https://api.github.com/repos/Taca-Ua/taca-ua-app"},"payload":{"ref":"accessability-changes","ref_type":"branch","full_ref":"refs/heads/accessability-changes","pusher_type":"user"},"public":true,"created_at":"2026-03-13T00:09:58Z","org":{"id":236881077,"login":"Taca-Ua","gravatar_id":"","url":"https://api.github.com/orgs/Taca-Ua","avatar_url":"https://avatars.githubusercontent.com/u/236881077?"}}]'

In [9]:
r.json()

[{'id': '9343575044',
  'type': 'PushEvent',
  'actor': {'id': 60653600,
   'login': 'mix113',
   'display_login': 'mix113',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/mix113',
   'avatar_url': 'https://avatars.githubusercontent.com/u/60653600?'},
  'repo': {'id': 1133518622,
   'name': 'mix113/leaders-image',
   'url': 'https://api.github.com/repos/mix113/leaders-image'},
  'payload': {'repository_id': 1133518622,
   'push_id': 31637129004,
   'ref': 'refs/heads/main',
   'head': 'bec34ef856853d276cf6945c9c80547cf55c496e',
   'before': '17277ccf4be1f4e8699c2ac0b806c895568da950'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575234',
  'type': 'PushEvent',
  'actor': {'id': 19983904,
   'login': 'lavraicse',
   'display_login': 'lavraicse',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/lavraicse',
   'avatar_url': 'https://avatars.githubusercontent.com/u/19983904?'},
  'repo': {'id': 1180332610,
   'name': 'lavraicse/githubpages-test',
   'url': 'https://api.github.com/repos/lavraicse/githubpages-test'},
  'payload': {'repository_id': 1180332610,
   'push_id': 31637129203,
   'ref': 'refs/heads/main',
   'head': 'c2a06f59cf733a39d450282972cd5efe23663c82',
   'before': '8653f2b7bc50ddeab773157d433ac73e9615338c'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575043',
  'type': 'PushEvent',
  'actor': {'id': 123560,
   'login': 'hughperkins',
   'display_login': 'hughperkins',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hughperkins',
   'avatar_url': 'https://avatars.githubusercontent.com/u/123560?'},
  'repo': {'id': 994002809,
   'name': 'Genesis-Embodied-AI/quadrants',
   'url': 'https://api.github.com/repos/Genesis-Embodied-AI/quadrants'},
  'payload': {'repository_id': 994002809,
   'push_id': 31637128988,
   'ref': 'refs/heads/main',
   'head': '450192a14987b8605c51228fd07caf703b8c589d',
   'before': 'fa4fa572af98b48287188d1f9221115e86680a62'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z',
  'org': {'id': 149333263,
   'login': 'Genesis-Embodied-AI',
   'gravatar_id': '',
   'url': 'https://api.github.com/orgs/Genesis-Embodied-AI',
   'avatar_url': 'https://avatars.githubusercontent.com/u/149333263?'}},
 {'id': '9343575326',
  'type': 'PushEvent',
  'actor': {'id': 111310114,
   'login': 'Anderfg13',
   'display_login': 'Anderfg13',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Anderfg13',
   'avatar_url': 'https://avatars.githubusercontent.com/u/111310114?'},
  'repo': {'id': 1180271486,
   'name': 'Anderfg13/Lab_P3_BluePrints_React_UI',
   'url': 'https://api.github.com/repos/Anderfg13/Lab_P3_BluePrints_React_UI'},
  'payload': {'repository_id': 1180271486,
   'push_id': 31637129230,
   'ref': 'refs/heads/main',
   'head': '8ed3468f0cdc94c74f9b2ccb12cfed567f23a462',
   'before': '4cf7d598957cc1ce85db65518be169503a7106b5'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575307',
  'type': 'PushEvent',
  'actor': {'id': 163665366,
   'login': 'shabazz007',
   'display_login': 'shabazz007',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/shabazz007',
   'avatar_url': 'https://avatars.githubusercontent.com/u/163665366?'},
  'repo': {'id': 1000700498,
   'name': 'shabazz007/bibfixer',
   'url': 'https://api.github.com/repos/shabazz007/bibfixer'},
  'payload': {'repository_id': 1000700498,
   'push_id': 31637129120,
   'ref': 'refs/heads/main',
   'head': 'e2793187866bb369f7d4074242c3bd686879341c',
   'before': '1ead1af56f2d972a219df24919511010ad6daa41'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575306',
  'type': 'PushEvent',
  'actor': {'id': 129240278,
   'login': 'SkyRaks',
   'display_login': 'SkyRaks',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/SkyRaks',
   'avatar_url': 'https://avatars.githubusercontent.com/u/129240278?'},
  'repo': {'id': 1122034243,
   'name': 'SkyRaks/CryptoAggregator',
   'url': 'https://api.github.com/repos/SkyRaks/CryptoAggregator'},
  'payload': {'repository_id': 1122034243,
   'push_id': 31637129206,
   'ref': 'refs/heads/main',
   'head': 'e00859db729c3b2568d6594e72d18e892bbb93f5',
   'before': '82fbe4e06255436941ddc3c7f4b1cbb9e570d6f5'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575288',
  'type': 'PushEvent',
  'actor': {'id': 204646541,
   'login': 'Whalica',
   'display_login': 'Whalica',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Whalica',
   'avatar_url': 'https://avatars.githubusercontent.com/u/204646541?'},
  'repo': {'id': 1174570277,
   'name': 'Whalica/Competitive_Programming_Notes',
   'url': 'https://api.github.com/repos/Whalica/Competitive_Programming_Notes'},
  'payload': {'repository_id': 1174570277,
   'push_id': 31637129147,
   'ref': 'refs/heads/main',
   'head': '53a49382efd9cac94d7d9096d606a463edc758fe',
   'before': '5d72021cc65c7f882192ea3b207b7adf2548b9bf'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575286',
  'type': 'PushEvent',
  'actor': {'id': 5831547,
   'login': 'cooleye',
   'display_login': 'cooleye',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/cooleye',
   'avatar_url': 'https://avatars.githubusercontent.com/u/5831547?'},
  'repo': {'id': 1179980934,
   'name': 'cooleye/private-traffic-system',
   'url': 'https://api.github.com/repos/cooleye/private-traffic-system'},
  'payload': {'repository_id': 1179980934,
   'push_id': 31637129271,
   'ref': 'refs/heads/main',
   'head': '1dfba5c12803368bc87483f7dca5bce49d7c0aaf',
   'before': '1e841895bfc368e51a310f0941e9a3bff45d249a'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575281',
  'type': 'PushEvent',
  'actor': {'id': 198982749,
   'login': 'Copilot',
   'display_login': 'copilot-swe-agent',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Copilot',
   'avatar_url': 'https://avatars.githubusercontent.com/u/198982749?'},
  'repo': {'id': 520721473,
   'name': 'barbrickdesign/barbrickdesign.github.io',
   'url': 'https://api.github.com/repos/barbrickdesign/barbrickdesign.github.io'},
  'payload': {'repository_id': 520721473,
   'push_id': 31637129173,
   'ref': 'refs/heads/copilot/remove-monthly-video-briefings',
   'head': 'ec9decf3e71f694cdb8c2bce9d0fc91a1b4636e4',
   'before': '061b560eb4e436a6272e07639aa584dceb5f0deb'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575267',
  'type': 'PushEvent',
  'actor': {'id': 254231878,
   'login': 'tomohikohorai-source',
   'display_login': 'tomohikohorai-source',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/tomohikohorai-source',
   'avatar_url': 'https://avatars.githubusercontent.com/u/254231878?'},
  'repo': {'id': 1132477041,
   'name': 'tomohikohorai-source/pjn-site',
   'url': 'https://api.github.com/repos/tomohikohorai-source/pjn-site'},
  'payload': {'repository_id': 1132477041,
   'push_id': 31637129167,
   'ref': 'refs/heads/main',
   'head': '92f0d32af132bcdcf18e01b8471d48436a55df0c',
   'before': 'f352a9d7ef5341d91420b66471576c59dfe0367b'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575252',
  'type': 'PushEvent',
  'actor': {'id': 1839708,
   'login': 'spali',
   'display_login': 'spali',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/spali',
   'avatar_url': 'https://avatars.githubusercontent.com/u/1839708?'},
  'repo': {'id': 565458011,
   'name': 'spali/esp-idf',
   'url': 'https://api.github.com/repos/spali/esp-idf'},
  'payload': {'repository_id': 565458011,
   'push_id': 31637129252,
   'ref': 'refs/heads/release/v5.1.5',
   'head': 'd63dfeb1092efd1463fe21ef0acb289e120fde92',
   'before': 'cb66fb1e0ba5aa81f8600c4e8010157b09f60ae0'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575247',
  'type': 'CreateEvent',
  'actor': {'id': 49699333,
   'login': 'dependabot[bot]',
   'display_login': 'dependabot',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/dependabot[bot]',
   'avatar_url': 'https://avatars.githubusercontent.com/u/49699333?'},
  'repo': {'id': 1180331025,
   'name': 'm3g/SFEModelling.jl',
   'url': 'https://api.github.com/repos/m3g/SFEModelling.jl'},
  'payload': {'ref': 'dependabot/github_actions/julia-actions/cache-3',
   'ref_type': 'branch',
   'full_ref': 'refs/heads/dependabot/github_actions/julia-actions/cache-3',
   'master_branch': 'main',
   'description': 'Supercritical Fluid Extraction data modeling tool',
   'pusher_type': 'user'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z',
  'org': {'id': 5021636,
   'login': 'm3g',
   'gravatar_id': '',
   'url': 'https://api.github.com/orgs/m3g',
   'avatar_url': 'https://avatars.githubusercontent.com/u/5021636?'}},
 {'id': '9343575241',
  'type': 'PushEvent',
  'actor': {'id': 159125892,
   'login': 'lovable-dev[bot]',
   'display_login': 'lovable-dev',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/lovable-dev[bot]',
   'avatar_url': 'https://avatars.githubusercontent.com/u/159125892?'},
  'repo': {'id': 1180284206,
   'name': 'alwardiabdo50-web/gentle-reader',
   'url': 'https://api.github.com/repos/alwardiabdo50-web/gentle-reader'},
  'payload': {'repository_id': 1180284206,
   'push_id': 31637129220,
   'ref': 'refs/heads/main',
   'head': '4e83792ab90422073fb79d8f55de91aa7c03d246',
   'before': 'e0223c3195fb84605c5cd915aa6509f6afad0505'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575034',
  'type': 'PushEvent',
  'actor': {'id': 200283118,
   'login': 'viciosO123',
   'display_login': 'viciosO123',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/viciosO123',
   'avatar_url': 'https://avatars.githubusercontent.com/u/200283118?'},
  'repo': {'id': 1077885341,
   'name': 'viciosO123/muon',
   'url': 'https://api.github.com/repos/viciosO123/muon'},
  'payload': {'repository_id': 1077885341,
   'push_id': 31637128925,
   'ref': 'refs/heads/main',
   'head': '76bf44ed9e096cf48ed23c16f1dea7e2d62be090',
   'before': '1ccd44f86955ab0c223ecfdc7c16a1a4b3accc28'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575224',
  'type': 'PushEvent',
  'actor': {'id': 1839708,
   'login': 'spali',
   'display_login': 'spali',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/spali',
   'avatar_url': 'https://avatars.githubusercontent.com/u/1839708?'},
  'repo': {'id': 565458011,
   'name': 'spali/esp-idf',
   'url': 'https://api.github.com/repos/spali/esp-idf'},
  'payload': {'repository_id': 565458011,
   'push_id': 31637129172,
   'ref': 'refs/heads/release/v4.3.3',
   'head': 'd7c1b1f01e79f59db6a888994ea4c7448238a02d',
   'before': '933ae3b1f43c8724297e29e0b00e66002f554b1b'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575223',
  'type': 'PushEvent',
  'actor': {'id': 2250046,
   'login': 'reiver',
   'display_login': 'reiver',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/reiver',
   'avatar_url': 'https://avatars.githubusercontent.com/u/2250046?'},
  'repo': {'id': 1180212882,
   'name': 'reiver/vibefed',
   'url': 'https://api.github.com/repos/reiver/vibefed'},
  'payload': {'repository_id': 1180212882,
   'push_id': 31637129123,
   'ref': 'refs/heads/master',
   'head': '179e2065dbc368687629b11a15ba20268a8893ce',
   'before': 'aec754ba1b3e2c156f4aca5e880bad1b8d454d77'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575215',
  'type': 'PushEvent',
  'actor': {'id': 267562634,
   'login': 'simonchangdevote',
   'display_login': 'simonchangdevote',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/simonchangdevote',
   'avatar_url': 'https://avatars.githubusercontent.com/u/267562634?'},
  'repo': {'id': 1179542722,
   'name': 'simonchangdevote/ambassador-platform',
   'url': 'https://api.github.com/repos/simonchangdevote/ambassador-platform'},
  'payload': {'repository_id': 1179542722,
   'push_id': 31637129086,
   'ref': 'refs/heads/main',
   'head': '24994d27477c09e94f1d5872d0427011008f0b98',
   'before': '3a5bbc1873057ea09250473bededdb10dc64a54e'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575207',
  'type': 'PushEvent',
  'actor': {'id': 197130100,
   'login': 'DIPPUSINHA',
   'display_login': 'DIPPUSINHA',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/DIPPUSINHA',
   'avatar_url': 'https://avatars.githubusercontent.com/u/197130100?'},
  'repo': {'id': 926119116,
   'name': 'DIPPUSINHA/Tg-Forwards',
   'url': 'https://api.github.com/repos/DIPPUSINHA/Tg-Forwards'},
  'payload': {'repository_id': 926119116,
   'push_id': 31637129082,
   'ref': 'refs/heads/main',
   'head': '0a8d086c9dd03cffca21e8de3cf84aa0a045b50d',
   'before': 'a00478cdd29ffdc3a1830d7a9ad69ec4f2879957'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575206',
  'type': 'PushEvent',
  'actor': {'id': 83982370,
   'login': 'Francis-Calingo',
   'display_login': 'Francis-Calingo',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Francis-Calingo',
   'avatar_url': 'https://avatars.githubusercontent.com/u/83982370?'},
  'repo': {'id': 838117588,
   'name': 'Francis-Calingo/francis-calingo',
   'url': 'https://api.github.com/repos/Francis-Calingo/francis-calingo'},
  'payload': {'repository_id': 838117588,
   'push_id': 31637129115,
   'ref': 'refs/heads/main',
   'head': '3dc9a58f6aeb4c9a780674e866338661149c123d',
   'before': '1f506308e9fcafa65d52c2d4fec1cc8b2f272539'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575202',
  'type': 'PushEvent',
  'actor': {'id': 166664864,
   'login': 'Dpfastner',
   'display_login': 'Dpfastner',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Dpfastner',
   'avatar_url': 'https://avatars.githubusercontent.com/u/166664864?'},
  'repo': {'id': 1142080842,
   'name': 'Dpfastner/fantasy-sports-platform',
   'url': 'https://api.github.com/repos/Dpfastner/fantasy-sports-platform'},
  'payload': {'repository_id': 1142080842,
   'push_id': 31637129204,
   'ref': 'refs/heads/main',
   'head': 'df1ea33369224b0d924e56dbca594c7972cd3f73',
   'before': '65ac474fb41cd1ab45327d3a32de755f116a5a48'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575191',
  'type': 'PushEvent',
  'actor': {'id': 15665609,
   'login': 'saitama45',
   'display_login': 'saitama45',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/saitama45',
   'avatar_url': 'https://avatars.githubusercontent.com/u/15665609?'},
  'repo': {'id': 1012847804,
   'name': 'saitama45/david',
   'url': 'https://api.github.com/repos/saitama45/david'},
  'payload': {'repository_id': 1012847804,
   'push_id': 31637129107,
   'ref': 'refs/heads/master',
   'head': '246f0330ffecc587fea54393592f1e78f3ad2a8e',
   'before': 'f67e26fe93851734a2c129eaa33fce07a9e83a56'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575183',
  'type': 'DeleteEvent',
  'actor': {'id': 8371576,
   'login': 'srbryers',
   'display_login': 'srbryers',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/srbryers',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8371576?'},
  'repo': {'id': 1162898953,
   'name': 'srbryers/slope',
   'url': 'https://api.github.com/repos/srbryers/slope'},
  'payload': {'ref': 'v1.25.2',
   'ref_type': 'tag',
   'full_ref': 'refs/tags/v1.25.2',
   'pusher_type': 'user'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575182',
  'type': 'PushEvent',
  'actor': {'id': 49736102,
   'login': 'kodiakhq[bot]',
   'display_login': 'kodiakhq',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/kodiakhq[bot]',
   'avatar_url': 'https://avatars.githubusercontent.com/u/49736102?'},
  'repo': {'id': 170304778,
   'name': 'ItinerisLtd/iroots',
   'url': 'https://api.github.com/repos/ItinerisLtd/iroots'},
  'payload': {'repository_id': 170304778,
   'push_id': 31637129098,
   'ref': 'refs/heads/master',
   'head': 'c5d2f55b8fc9c836a434bd0bd2a3aa2de77cf7b4',
   'before': 'b7fc0d4a631e4f8cc16fbf013cd9c51a2f298297'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z',
  'org': {'id': 32365928,
   'login': 'ItinerisLtd',
   'gravatar_id': '',
   'url': 'https://api.github.com/orgs/ItinerisLtd',
   'avatar_url': 'https://avatars.githubusercontent.com/u/32365928?'}},
 {'id': '9343575178',
  'type': 'PushEvent',
  'actor': {'id': 178097291,
   'login': 'ppl-committer',
   'display_login': 'ppl-committer',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/ppl-committer',
   'avatar_url': 'https://avatars.githubusercontent.com/u/178097291?'},
  'repo': {'id': 834941258,
   'name': 'pewpewlive/ppl-data',
   'url': 'https://api.github.com/repos/pewpewlive/ppl-data'},
  'payload': {'repository_id': 834941258,
   'push_id': 31637129080,
   'ref': 'refs/heads/master',
   'head': 'c61cd1fa299071635e389143ddf5f14706fa280e',
   'before': '6c12cd2f1d95196b8ed737c462dd08fa2cd38fce'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z',
  'org': {'id': 109729559,
   'login': 'pewpewlive',
   'gravatar_id': '',
   'url': 'https://api.github.com/orgs/pewpewlive',
   'avatar_url': 'https://avatars.githubusercontent.com/u/109729559?'}},
 {'id': '9343575175',
  'type': 'PushEvent',
  'actor': {'id': 28951336,
   'login': 'Spikewmu',
   'display_login': 'Spikewmu',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Spikewmu',
   'avatar_url': 'https://avatars.githubusercontent.com/u/28951336?'},
  'repo': {'id': 1159670668,
   'name': 'Spikewmu/n8n-workflow-backups2026',
   'url': 'https://api.github.com/repos/Spikewmu/n8n-workflow-backups2026'},
  'payload': {'repository_id': 1159670668,
   'push_id': 31637129113,
   'ref': 'refs/heads/main',
   'head': '1bc8188ff5b8120fe396dca50fdfa0266d227e2e',
   'before': '9abe387ed77d04b652f2be7911484a921d1ca330'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575161',
  'type': 'PushEvent',
  'actor': {'id': 1839708,
   'login': 'spali',
   'display_login': 'spali',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/spali',
   'avatar_url': 'https://avatars.githubusercontent.com/u/1839708?'},
  'repo': {'id': 565458011,
   'name': 'spali/esp-idf',
   'url': 'https://api.github.com/repos/spali/esp-idf'},
  'payload': {'repository_id': 565458011,
   'push_id': 31637129095,
   'ref': 'refs/heads/release/v4.4.2',
   'head': 'deccae0fc09d581feca0feb48dd93d9b71cebedc',
   'before': '0215c97ba8498eac4a5b548f6f0265e9c5a61089'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575158',
  'type': 'PushEvent',
  'actor': {'id': 153868092,
   'login': 'KaykyOne',
   'display_login': 'KaykyOne',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/KaykyOne',
   'avatar_url': 'https://avatars.githubusercontent.com/u/153868092?'},
  'repo': {'id': 1126369143,
   'name': 'KaykyOne/novus-cfc',
   'url': 'https://api.github.com/repos/KaykyOne/novus-cfc'},
  'payload': {'repository_id': 1126369143,
   'push_id': 31637129045,
   'ref': 'refs/heads/dev',
   'head': '957bbc85ad4f0caa790437da35288dacd21db461',
   'before': '0b50820636ea6402845dd27716257dd1d3e886d1'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575153',
  'type': 'PushEvent',
  'actor': {'id': 41898282,
   'login': 'github-actions[bot]',
   'display_login': 'github-actions',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/github-actions[bot]',
   'avatar_url': 'https://avatars.githubusercontent.com/u/41898282?'},
  'repo': {'id': 741524414,
   'name': 'hey-api/openapi-ts',
   'url': 'https://api.github.com/repos/hey-api/openapi-ts'},
  'payload': {'repository_id': 741524414,
   'push_id': 31637129039,
   'ref': 'refs/heads/main',
   'head': 'e88abc67656064aa7de338e781f0970b1f316ca3',
   'before': '7fe03ab5e3e74febe1a546d412eef72e745000aa'},

In [10]:
r = requests.get('https://api.github.com/versions')
r.text

'["2026-03-10","2022-11-28"]'

In [11]:
headers = {'X-GitHub-Api-Version': '2022-11-28'}
r = requests.get('https://api.github.com/events', headers=headers)
r.json()

[{'id': '9343575044',
  'type': 'PushEvent',
  'actor': {'id': 60653600,
   'login': 'mix113',
   'display_login': 'mix113',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/mix113',
   'avatar_url': 'https://avatars.githubusercontent.com/u/60653600?'},
  'repo': {'id': 1133518622,
   'name': 'mix113/leaders-image',
   'url': 'https://api.github.com/repos/mix113/leaders-image'},
  'payload': {'repository_id': 1133518622,
   'push_id': 31637129004,
   'ref': 'refs/heads/main',
   'head': 'bec34ef856853d276cf6945c9c80547cf55c496e',
   'before': '17277ccf4be1f4e8699c2ac0b806c895568da950'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575234',
  'type': 'PushEvent',
  'actor': {'id': 19983904,
   'login': 'lavraicse',
   'display_login': 'lavraicse',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/lavraicse',
   'avatar_url': 'https://avatars.githubusercontent.com/u/19983904?'},
  'repo': {'id': 1180332610,
   'name': 'lavraicse/githubpages-test',
   'url': 'https://api.github.com/repos/lavraicse/githubpages-test'},
  'payload': {'repository_id': 1180332610,
   'push_id': 31637129203,
   'ref': 'refs/heads/main',
   'head': 'c2a06f59cf733a39d450282972cd5efe23663c82',
   'before': '8653f2b7bc50ddeab773157d433ac73e9615338c'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575043',
  'type': 'PushEvent',
  'actor': {'id': 123560,
   'login': 'hughperkins',
   'display_login': 'hughperkins',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hughperkins',
   'avatar_url': 'https://avatars.githubusercontent.com/u/123560?'},
  'repo': {'id': 994002809,
   'name': 'Genesis-Embodied-AI/quadrants',
   'url': 'https://api.github.com/repos/Genesis-Embodied-AI/quadrants'},
  'payload': {'repository_id': 994002809,
   'push_id': 31637128988,
   'ref': 'refs/heads/main',
   'head': '450192a14987b8605c51228fd07caf703b8c589d',
   'before': 'fa4fa572af98b48287188d1f9221115e86680a62'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z',
  'org': {'id': 149333263,
   'login': 'Genesis-Embodied-AI',
   'gravatar_id': '',
   'url': 'https://api.github.com/orgs/Genesis-Embodied-AI',
   'avatar_url': 'https://avatars.githubusercontent.com/u/149333263?'}},
 {'id': '9343575326',
  'type': 'PushEvent',
  'actor': {'id': 111310114,
   'login': 'Anderfg13',
   'display_login': 'Anderfg13',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Anderfg13',
   'avatar_url': 'https://avatars.githubusercontent.com/u/111310114?'},
  'repo': {'id': 1180271486,
   'name': 'Anderfg13/Lab_P3_BluePrints_React_UI',
   'url': 'https://api.github.com/repos/Anderfg13/Lab_P3_BluePrints_React_UI'},
  'payload': {'repository_id': 1180271486,
   'push_id': 31637129230,
   'ref': 'refs/heads/main',
   'head': '8ed3468f0cdc94c74f9b2ccb12cfed567f23a462',
   'before': '4cf7d598957cc1ce85db65518be169503a7106b5'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575307',
  'type': 'PushEvent',
  'actor': {'id': 163665366,
   'login': 'shabazz007',
   'display_login': 'shabazz007',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/shabazz007',
   'avatar_url': 'https://avatars.githubusercontent.com/u/163665366?'},
  'repo': {'id': 1000700498,
   'name': 'shabazz007/bibfixer',
   'url': 'https://api.github.com/repos/shabazz007/bibfixer'},
  'payload': {'repository_id': 1000700498,
   'push_id': 31637129120,
   'ref': 'refs/heads/main',
   'head': 'e2793187866bb369f7d4074242c3bd686879341c',
   'before': '1ead1af56f2d972a219df24919511010ad6daa41'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575306',
  'type': 'PushEvent',
  'actor': {'id': 129240278,
   'login': 'SkyRaks',
   'display_login': 'SkyRaks',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/SkyRaks',
   'avatar_url': 'https://avatars.githubusercontent.com/u/129240278?'},
  'repo': {'id': 1122034243,
   'name': 'SkyRaks/CryptoAggregator',
   'url': 'https://api.github.com/repos/SkyRaks/CryptoAggregator'},
  'payload': {'repository_id': 1122034243,
   'push_id': 31637129206,
   'ref': 'refs/heads/main',
   'head': 'e00859db729c3b2568d6594e72d18e892bbb93f5',
   'before': '82fbe4e06255436941ddc3c7f4b1cbb9e570d6f5'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575288',
  'type': 'PushEvent',
  'actor': {'id': 204646541,
   'login': 'Whalica',
   'display_login': 'Whalica',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Whalica',
   'avatar_url': 'https://avatars.githubusercontent.com/u/204646541?'},
  'repo': {'id': 1174570277,
   'name': 'Whalica/Competitive_Programming_Notes',
   'url': 'https://api.github.com/repos/Whalica/Competitive_Programming_Notes'},
  'payload': {'repository_id': 1174570277,
   'push_id': 31637129147,
   'ref': 'refs/heads/main',
   'head': '53a49382efd9cac94d7d9096d606a463edc758fe',
   'before': '5d72021cc65c7f882192ea3b207b7adf2548b9bf'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575286',
  'type': 'PushEvent',
  'actor': {'id': 5831547,
   'login': 'cooleye',
   'display_login': 'cooleye',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/cooleye',
   'avatar_url': 'https://avatars.githubusercontent.com/u/5831547?'},
  'repo': {'id': 1179980934,
   'name': 'cooleye/private-traffic-system',
   'url': 'https://api.github.com/repos/cooleye/private-traffic-system'},
  'payload': {'repository_id': 1179980934,
   'push_id': 31637129271,
   'ref': 'refs/heads/main',
   'head': '1dfba5c12803368bc87483f7dca5bce49d7c0aaf',
   'before': '1e841895bfc368e51a310f0941e9a3bff45d249a'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575281',
  'type': 'PushEvent',
  'actor': {'id': 198982749,
   'login': 'Copilot',
   'display_login': 'copilot-swe-agent',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Copilot',
   'avatar_url': 'https://avatars.githubusercontent.com/u/198982749?'},
  'repo': {'id': 520721473,
   'name': 'barbrickdesign/barbrickdesign.github.io',
   'url': 'https://api.github.com/repos/barbrickdesign/barbrickdesign.github.io'},
  'payload': {'repository_id': 520721473,
   'push_id': 31637129173,
   'ref': 'refs/heads/copilot/remove-monthly-video-briefings',
   'head': 'ec9decf3e71f694cdb8c2bce9d0fc91a1b4636e4',
   'before': '061b560eb4e436a6272e07639aa584dceb5f0deb'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575267',
  'type': 'PushEvent',
  'actor': {'id': 254231878,
   'login': 'tomohikohorai-source',
   'display_login': 'tomohikohorai-source',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/tomohikohorai-source',
   'avatar_url': 'https://avatars.githubusercontent.com/u/254231878?'},
  'repo': {'id': 1132477041,
   'name': 'tomohikohorai-source/pjn-site',
   'url': 'https://api.github.com/repos/tomohikohorai-source/pjn-site'},
  'payload': {'repository_id': 1132477041,
   'push_id': 31637129167,
   'ref': 'refs/heads/main',
   'head': '92f0d32af132bcdcf18e01b8471d48436a55df0c',
   'before': 'f352a9d7ef5341d91420b66471576c59dfe0367b'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575252',
  'type': 'PushEvent',
  'actor': {'id': 1839708,
   'login': 'spali',
   'display_login': 'spali',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/spali',
   'avatar_url': 'https://avatars.githubusercontent.com/u/1839708?'},
  'repo': {'id': 565458011,
   'name': 'spali/esp-idf',
   'url': 'https://api.github.com/repos/spali/esp-idf'},
  'payload': {'repository_id': 565458011,
   'push_id': 31637129252,
   'ref': 'refs/heads/release/v5.1.5',
   'head': 'd63dfeb1092efd1463fe21ef0acb289e120fde92',
   'before': 'cb66fb1e0ba5aa81f8600c4e8010157b09f60ae0'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575247',
  'type': 'CreateEvent',
  'actor': {'id': 49699333,
   'login': 'dependabot[bot]',
   'display_login': 'dependabot',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/dependabot[bot]',
   'avatar_url': 'https://avatars.githubusercontent.com/u/49699333?'},
  'repo': {'id': 1180331025,
   'name': 'm3g/SFEModelling.jl',
   'url': 'https://api.github.com/repos/m3g/SFEModelling.jl'},
  'payload': {'ref': 'dependabot/github_actions/julia-actions/cache-3',
   'ref_type': 'branch',
   'full_ref': 'refs/heads/dependabot/github_actions/julia-actions/cache-3',
   'master_branch': 'main',
   'description': 'Supercritical Fluid Extraction data modeling tool',
   'pusher_type': 'user'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z',
  'org': {'id': 5021636,
   'login': 'm3g',
   'gravatar_id': '',
   'url': 'https://api.github.com/orgs/m3g',
   'avatar_url': 'https://avatars.githubusercontent.com/u/5021636?'}},
 {'id': '9343575241',
  'type': 'PushEvent',
  'actor': {'id': 159125892,
   'login': 'lovable-dev[bot]',
   'display_login': 'lovable-dev',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/lovable-dev[bot]',
   'avatar_url': 'https://avatars.githubusercontent.com/u/159125892?'},
  'repo': {'id': 1180284206,
   'name': 'alwardiabdo50-web/gentle-reader',
   'url': 'https://api.github.com/repos/alwardiabdo50-web/gentle-reader'},
  'payload': {'repository_id': 1180284206,
   'push_id': 31637129220,
   'ref': 'refs/heads/main',
   'head': '4e83792ab90422073fb79d8f55de91aa7c03d246',
   'before': 'e0223c3195fb84605c5cd915aa6509f6afad0505'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575034',
  'type': 'PushEvent',
  'actor': {'id': 200283118,
   'login': 'viciosO123',
   'display_login': 'viciosO123',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/viciosO123',
   'avatar_url': 'https://avatars.githubusercontent.com/u/200283118?'},
  'repo': {'id': 1077885341,
   'name': 'viciosO123/muon',
   'url': 'https://api.github.com/repos/viciosO123/muon'},
  'payload': {'repository_id': 1077885341,
   'push_id': 31637128925,
   'ref': 'refs/heads/main',
   'head': '76bf44ed9e096cf48ed23c16f1dea7e2d62be090',
   'before': '1ccd44f86955ab0c223ecfdc7c16a1a4b3accc28'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575224',
  'type': 'PushEvent',
  'actor': {'id': 1839708,
   'login': 'spali',
   'display_login': 'spali',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/spali',
   'avatar_url': 'https://avatars.githubusercontent.com/u/1839708?'},
  'repo': {'id': 565458011,
   'name': 'spali/esp-idf',
   'url': 'https://api.github.com/repos/spali/esp-idf'},
  'payload': {'repository_id': 565458011,
   'push_id': 31637129172,
   'ref': 'refs/heads/release/v4.3.3',
   'head': 'd7c1b1f01e79f59db6a888994ea4c7448238a02d',
   'before': '933ae3b1f43c8724297e29e0b00e66002f554b1b'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575223',
  'type': 'PushEvent',
  'actor': {'id': 2250046,
   'login': 'reiver',
   'display_login': 'reiver',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/reiver',
   'avatar_url': 'https://avatars.githubusercontent.com/u/2250046?'},
  'repo': {'id': 1180212882,
   'name': 'reiver/vibefed',
   'url': 'https://api.github.com/repos/reiver/vibefed'},
  'payload': {'repository_id': 1180212882,
   'push_id': 31637129123,
   'ref': 'refs/heads/master',
   'head': '179e2065dbc368687629b11a15ba20268a8893ce',
   'before': 'aec754ba1b3e2c156f4aca5e880bad1b8d454d77'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575215',
  'type': 'PushEvent',
  'actor': {'id': 267562634,
   'login': 'simonchangdevote',
   'display_login': 'simonchangdevote',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/simonchangdevote',
   'avatar_url': 'https://avatars.githubusercontent.com/u/267562634?'},
  'repo': {'id': 1179542722,
   'name': 'simonchangdevote/ambassador-platform',
   'url': 'https://api.github.com/repos/simonchangdevote/ambassador-platform'},
  'payload': {'repository_id': 1179542722,
   'push_id': 31637129086,
   'ref': 'refs/heads/main',
   'head': '24994d27477c09e94f1d5872d0427011008f0b98',
   'before': '3a5bbc1873057ea09250473bededdb10dc64a54e'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575207',
  'type': 'PushEvent',
  'actor': {'id': 197130100,
   'login': 'DIPPUSINHA',
   'display_login': 'DIPPUSINHA',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/DIPPUSINHA',
   'avatar_url': 'https://avatars.githubusercontent.com/u/197130100?'},
  'repo': {'id': 926119116,
   'name': 'DIPPUSINHA/Tg-Forwards',
   'url': 'https://api.github.com/repos/DIPPUSINHA/Tg-Forwards'},
  'payload': {'repository_id': 926119116,
   'push_id': 31637129082,
   'ref': 'refs/heads/main',
   'head': '0a8d086c9dd03cffca21e8de3cf84aa0a045b50d',
   'before': 'a00478cdd29ffdc3a1830d7a9ad69ec4f2879957'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575206',
  'type': 'PushEvent',
  'actor': {'id': 83982370,
   'login': 'Francis-Calingo',
   'display_login': 'Francis-Calingo',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Francis-Calingo',
   'avatar_url': 'https://avatars.githubusercontent.com/u/83982370?'},
  'repo': {'id': 838117588,
   'name': 'Francis-Calingo/francis-calingo',
   'url': 'https://api.github.com/repos/Francis-Calingo/francis-calingo'},
  'payload': {'repository_id': 838117588,
   'push_id': 31637129115,
   'ref': 'refs/heads/main',
   'head': '3dc9a58f6aeb4c9a780674e866338661149c123d',
   'before': '1f506308e9fcafa65d52c2d4fec1cc8b2f272539'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575202',
  'type': 'PushEvent',
  'actor': {'id': 166664864,
   'login': 'Dpfastner',
   'display_login': 'Dpfastner',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Dpfastner',
   'avatar_url': 'https://avatars.githubusercontent.com/u/166664864?'},
  'repo': {'id': 1142080842,
   'name': 'Dpfastner/fantasy-sports-platform',
   'url': 'https://api.github.com/repos/Dpfastner/fantasy-sports-platform'},
  'payload': {'repository_id': 1142080842,
   'push_id': 31637129204,
   'ref': 'refs/heads/main',
   'head': 'df1ea33369224b0d924e56dbca594c7972cd3f73',
   'before': '65ac474fb41cd1ab45327d3a32de755f116a5a48'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575191',
  'type': 'PushEvent',
  'actor': {'id': 15665609,
   'login': 'saitama45',
   'display_login': 'saitama45',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/saitama45',
   'avatar_url': 'https://avatars.githubusercontent.com/u/15665609?'},
  'repo': {'id': 1012847804,
   'name': 'saitama45/david',
   'url': 'https://api.github.com/repos/saitama45/david'},
  'payload': {'repository_id': 1012847804,
   'push_id': 31637129107,
   'ref': 'refs/heads/master',
   'head': '246f0330ffecc587fea54393592f1e78f3ad2a8e',
   'before': 'f67e26fe93851734a2c129eaa33fce07a9e83a56'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575183',
  'type': 'DeleteEvent',
  'actor': {'id': 8371576,
   'login': 'srbryers',
   'display_login': 'srbryers',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/srbryers',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8371576?'},
  'repo': {'id': 1162898953,
   'name': 'srbryers/slope',
   'url': 'https://api.github.com/repos/srbryers/slope'},
  'payload': {'ref': 'v1.25.2',
   'ref_type': 'tag',
   'full_ref': 'refs/tags/v1.25.2',
   'pusher_type': 'user'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575182',
  'type': 'PushEvent',
  'actor': {'id': 49736102,
   'login': 'kodiakhq[bot]',
   'display_login': 'kodiakhq',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/kodiakhq[bot]',
   'avatar_url': 'https://avatars.githubusercontent.com/u/49736102?'},
  'repo': {'id': 170304778,
   'name': 'ItinerisLtd/iroots',
   'url': 'https://api.github.com/repos/ItinerisLtd/iroots'},
  'payload': {'repository_id': 170304778,
   'push_id': 31637129098,
   'ref': 'refs/heads/master',
   'head': 'c5d2f55b8fc9c836a434bd0bd2a3aa2de77cf7b4',
   'before': 'b7fc0d4a631e4f8cc16fbf013cd9c51a2f298297'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z',
  'org': {'id': 32365928,
   'login': 'ItinerisLtd',
   'gravatar_id': '',
   'url': 'https://api.github.com/orgs/ItinerisLtd',
   'avatar_url': 'https://avatars.githubusercontent.com/u/32365928?'}},
 {'id': '9343575178',
  'type': 'PushEvent',
  'actor': {'id': 178097291,
   'login': 'ppl-committer',
   'display_login': 'ppl-committer',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/ppl-committer',
   'avatar_url': 'https://avatars.githubusercontent.com/u/178097291?'},
  'repo': {'id': 834941258,
   'name': 'pewpewlive/ppl-data',
   'url': 'https://api.github.com/repos/pewpewlive/ppl-data'},
  'payload': {'repository_id': 834941258,
   'push_id': 31637129080,
   'ref': 'refs/heads/master',
   'head': 'c61cd1fa299071635e389143ddf5f14706fa280e',
   'before': '6c12cd2f1d95196b8ed737c462dd08fa2cd38fce'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z',
  'org': {'id': 109729559,
   'login': 'pewpewlive',
   'gravatar_id': '',
   'url': 'https://api.github.com/orgs/pewpewlive',
   'avatar_url': 'https://avatars.githubusercontent.com/u/109729559?'}},
 {'id': '9343575175',
  'type': 'PushEvent',
  'actor': {'id': 28951336,
   'login': 'Spikewmu',
   'display_login': 'Spikewmu',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Spikewmu',
   'avatar_url': 'https://avatars.githubusercontent.com/u/28951336?'},
  'repo': {'id': 1159670668,
   'name': 'Spikewmu/n8n-workflow-backups2026',
   'url': 'https://api.github.com/repos/Spikewmu/n8n-workflow-backups2026'},
  'payload': {'repository_id': 1159670668,
   'push_id': 31637129113,
   'ref': 'refs/heads/main',
   'head': '1bc8188ff5b8120fe396dca50fdfa0266d227e2e',
   'before': '9abe387ed77d04b652f2be7911484a921d1ca330'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575161',
  'type': 'PushEvent',
  'actor': {'id': 1839708,
   'login': 'spali',
   'display_login': 'spali',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/spali',
   'avatar_url': 'https://avatars.githubusercontent.com/u/1839708?'},
  'repo': {'id': 565458011,
   'name': 'spali/esp-idf',
   'url': 'https://api.github.com/repos/spali/esp-idf'},
  'payload': {'repository_id': 565458011,
   'push_id': 31637129095,
   'ref': 'refs/heads/release/v4.4.2',
   'head': 'deccae0fc09d581feca0feb48dd93d9b71cebedc',
   'before': '0215c97ba8498eac4a5b548f6f0265e9c5a61089'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575158',
  'type': 'PushEvent',
  'actor': {'id': 153868092,
   'login': 'KaykyOne',
   'display_login': 'KaykyOne',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/KaykyOne',
   'avatar_url': 'https://avatars.githubusercontent.com/u/153868092?'},
  'repo': {'id': 1126369143,
   'name': 'KaykyOne/novus-cfc',
   'url': 'https://api.github.com/repos/KaykyOne/novus-cfc'},
  'payload': {'repository_id': 1126369143,
   'push_id': 31637129045,
   'ref': 'refs/heads/dev',
   'head': '957bbc85ad4f0caa790437da35288dacd21db461',
   'before': '0b50820636ea6402845dd27716257dd1d3e886d1'},
  'public': True,
  'created_at': '2026-03-13T00:09:58Z'},
 {'id': '9343575153',
  'type': 'PushEvent',
  'actor': {'id': 41898282,
   'login': 'github-actions[bot]',
   'display_login': 'github-actions',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/github-actions[bot]',
   'avatar_url': 'https://avatars.githubusercontent.com/u/41898282?'},
  'repo': {'id': 741524414,
   'name': 'hey-api/openapi-ts',
   'url': 'https://api.github.com/repos/hey-api/openapi-ts'},
  'payload': {'repository_id': 741524414,
   'push_id': 31637129039,
   'ref': 'refs/heads/main',
   'head': 'e88abc67656064aa7de338e781f0970b1f316ca3',
   'before': '7fe03ab5e3e74febe1a546d412eef72e745000aa'},

In [12]:
" DESAFIO 1 - Faça uma requisição pegando os dados de um Usuário do GitHub "

req = requests.get('https://api.github.com/users/rdzvergara')
req.status_code

200

In [13]:
req.json()

{'login': 'rdzvergara',
 'id': 48964173,
 'node_id': 'MDQ6VXNlcjQ4OTY0MTcz',
 'avatar_url': 'https://avatars.githubusercontent.com/u/48964173?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/rdzvergara',
 'html_url': 'https://github.com/rdzvergara',
 'followers_url': 'https://api.github.com/users/rdzvergara/followers',
 'following_url': 'https://api.github.com/users/rdzvergara/following{/other_user}',
 'gists_url': 'https://api.github.com/users/rdzvergara/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/rdzvergara/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/rdzvergara/subscriptions',
 'organizations_url': 'https://api.github.com/users/rdzvergara/orgs',
 'repos_url': 'https://api.github.com/users/rdzvergara/repos',
 'events_url': 'https://api.github.com/users/rdzvergara/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/rdzvergara/received_events',
 'type': 'User',
 'user_view_type': 'public',
 'site_admin': False,
 'name': 'Rodrigo Luiz de Mattos Vergara',
 'company': None,
 'blog': '',
 'location': None,
 'email': None,
 'hireable': None,
 'bio': None,
 'twitter_username': None,
 'public_repos': 8,
 'public_gists': 0,
 'followers': 8,
 'following': 6,
 'created_at': '2019-03-26T18:54:59Z',
 'updated_at': '2026-03-10T02:13:09Z'}

In [14]:
req.url

'https://api.github.com/users/rdzvergara'

In [15]:
data = req.json()

resposta = { 
    'name': data.get('name'),
    'login': data.get('login'),
    'public_repos': data.get('public_repos'),
    'created_at': data.get('created_at')
    }

print(resposta)

{'name': 'Rodrigo Luiz de Mattos Vergara', 'login': 'rdzvergara', 'public_repos': 8, 'created_at': '2019-03-26T18:54:59Z'}

In [16]:
headers = {'X-GitHub-Api-Version': '2022-11-28'}

In [17]:
api_base_url = 'https://api.github.com'
owner = 'amzn' # Usuário que vamos extrair os dados
url = f'{api_base_url}/users/{owner}'

In [18]:
resposta = requests.get(url, headers=headers)
resposta.status_code

200

In [19]:
resposta.json()

{'login': 'amzn',
 'id': 8594673,
 'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
 'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/amzn',
 'html_url': 'https://github.com/amzn',
 'followers_url': 'https://api.github.com/users/amzn/followers',
 'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
 'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
 'organizations_url': 'https://api.github.com/users/amzn/orgs',
 'repos_url': 'https://api.github.com/users/amzn/repos',
 'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/amzn/received_events',
 'type': 'Organization',
 'user_view_type': 'public',
 'site_admin': False,
 'name': 'Amazon',
 'company': None,
 'blog': 'https://developer.amazon.com/',
 'location': None,
 'email': None,
 'hireable': None,
 'bio': None,
 'twitter_username': None,
 'public_repos': 166,
 'public_gists': 0,
 'followers': 2515,
 'following': 0,
 'created_at': '2014-08-29T21:50:46Z',
 'updated_at': '2025-05-01T16:25:54Z'}

In [20]:
len(resposta.json())

33

In [21]:
accesss_token = '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'
headers = {
    'X-GitHub-Api-Version': '2022-11-28',
    'Authorization': 'Bearer ' + accesss_token
}

In [22]:
api_base_url = 'https://api.github.com'
owner = 'amzn' # Usuário que vamos extrair os dados
url = f'{api_base_url}/users/{owner}/repos'

In [23]:
repos_list = []
for page_num in range(1, 6):
    try:
        url_page = f'{url}?page={page_num}'
        resposta = requests.get(url_page, headers= headers)
        repos_list.append(resposta.json())
    except:
        repos_list.append(None)

In [24]:
repos_list

[[{'id': 171339259,
   'node_id': 'MDEwOlJlcG9zaXRvcnkxNzEzMzkyNTk=',
   'name': '.github',
   'full_name': 'amzn/.github',
   'private': False,
   'owner': {'login': 'amzn',
    'id': 8594673,
    'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
    'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/amzn',
    'html_url': 'https://github.com/amzn',
    'followers_url': 'https://api.github.com/users/amzn/followers',
    'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
    'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
    'organizations_url': 'https://api.github.com/users/amzn/orgs',
    'repos_url': 'https://api.github.com/users/amzn/repos',
    'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/amzn/received_events',
    'type': 'Organization',
    'user_view_type': 'public',
    'site_admin': False},
   'html_url': 'https://github.com/amzn/.github',
   'description': None,
   'fork': False,
   'url': 'https://api.github.com/repos/amzn/.github',
   'forks_url': 'https://api.github.com/repos/amzn/.github/forks',
   'keys_url': 'https://api.github.com/repos/amzn/.github/keys{/key_id}',
   'collaborators_url': 'https://api.github.com/repos/amzn/.github/collaborators{/collaborator}',
   'teams_url': 'https://api.github.com/repos/amzn/.github/teams',
   'hooks_url': 'https://api.github.com/repos/amzn/.github/hooks',
   'issue_events_url': 'https://api.github.com/repos/amzn/.github/issues/events{/number}',
   'events_url': 'https://api.github.com/repos/amzn/.github/events',
   'assignees_url': 'https://api.github.com/repos/amzn/.github/assignees{/user}',
   'branches_url': 'https://api.github.com/repos/amzn/.github/branches{/branch}',
   'tags_url': 'https://api.github.com/repos/amzn/.github/tags',
   'blobs_url': 'https://api.github.com/repos/amzn/.github/git/blobs{/sha}',
   'git_tags_url': 'https://api.github.com/repos/amzn/.github/git/tags{/sha}',
   'git_refs_url': 'https://api.github.com/repos/amzn/.github/git/refs{/sha}',
   'trees_url': 'https://api.github.com/repos/amzn/.github/git/trees{/sha}',
   'statuses_url': 'https://api.github.com/repos/amzn/.github/statuses/{sha}',
   'languages_url': 'https://api.github.com/repos/amzn/.github/languages',
   'stargazers_url': 'https://api.github.com/repos/amzn/.github/stargazers',
   'contributors_url': 'https://api.github.com/repos/amzn/.github/contributors',
   'subscribers_url': 'https://api.github.com/repos/amzn/.github/subscribers',
   'subscription_url': 'https://api.github.com/repos/amzn/.github/subscription',
   'commits_url': 'https://api.github.com/repos/amzn/.github/commits{/sha}',
   'git_commits_url': 'https://api.github.com/repos/amzn/.github/git/commits{/sha}',
   'comments_url': 'https://api.github.com/repos/amzn/.github/comments{/number}',
   'issue_comment_url': 'https://api.github.com/repos/amzn/.github/issues/comments{/number}',
   'contents_url': 'https://api.github.com/repos/amzn/.github/contents/{+path}',
   'compare_url': 'https://api.github.com/repos/amzn/.github/compare/{base}...{head}',
   'merges_url': 'https://api.github.com/repos/amzn/.github/merges',
   'archive_url': 'https://api.github.com/repos/amzn/.github/{archive_format}{/ref}',
   'downloads_url': 'https://api.github.com/repos/amzn/.github/downloads',
   'issues_url': 'https://api.github.com/repos/amzn/.github/issues{/number}',
   'pulls_url': 'https://api.github.com/repos/amzn/.github/pulls{/number}',
   'milestones_url': 'https://api.github.com/repos/amzn/.github/milestones{/number}',
   'notifications_url': 'https://api.github.com/repos/amzn/.github/notifications{?since,all,participating}',
   'labels_url': 'https://api.github.com/repos/amzn/.github/labels{/name}',
   'releases_url': 'https://api.github.com/repos/amzn/.github/releases{/id}',
   'deployments_url': 'https://api.github.com/repos/amzn/.github/deployments',
   'created_at': '2019-02-18T18:59:22Z',
   'updated_at': '2026-01-12T04:08:52Z',
   'pushed_at': '2024-10-18T22:23:05Z',
   'git_url': 'git://github.com/amzn/.github.git',
   'ssh_url': 'git@github.com:amzn/.github.git',
   'clone_url': 'https://github.com/amzn/.github.git',
   'svn_url': 'https://github.com/amzn/.github',
   'homepage': None,
   'size': 24,
   'stargazers_count': 20,
   'watchers_count': 20,
   'language': None,
   'has_issues': True,
   'has_projects': False,
   'has_downloads': True,
   'has_wiki': False,
   'has_pages': False,
   'has_discussions': False,
   'forks_count': 439,
   'mirror_url': None,
   'archived': False,
   'disabled': False,
   'open_issues_count': 3,
   'license': None,
   'allow_forking': True,
   'is_template': False,
   'web_commit_signoff_required': False,
   'has_pull_requests': True,
   'pull_request_creation_policy': 'all',
   'topics': [],
   'visibility': 'public',
   'forks': 439,
   'open_issues': 3,
   'watchers': 20,
   'default_branch': 'master',
   'permissions': {'admin': False,
    'maintain': False,
    'push': False,
    'triage': False,
    'pull': True}},
  {'id': 492978607,
   'node_id': 'R_kgDOHWJBrw',
   'name': 'ads-advanced-tools-docs',
   'full_name': 'amzn/ads-advanced-tools-docs',
   'private': False,
   'owner': {'login': 'amzn',
    'id': 8594673,
    'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
    'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/amzn',
    'html_url': 'https://github.com/amzn',
    'followers_url': 'https://api.github.com/users/amzn/followers',
    'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
    'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
    'organizations_url': 'https://api.github.com/users/amzn/orgs',
    'repos_url': 'https://api.github.com/users/amzn/repos',
    'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/amzn/received_events',
    'type': 'Organization',
    'user_view_type': 'public',
    'site_admin': False},
   'html_url': 'https://github.com/amzn/ads-advanced-tools-docs',
   'description': 'Code samples and supplements for the Amazon Ads advanced tools center',
   'fork': False,
   'url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs',
   'forks_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/forks',
   'keys_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/keys{/key_id}',
   'collaborators_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/collaborators{/collaborator}',
   'teams_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/teams',
   'hooks_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/hooks',
   'issue_events_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues/events{/number}',
   'events_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/events',
   'assignees_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/assignees{/user}',
   'branches_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/branches{/branch}',
   'tags_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/tags',
   'blobs_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/blobs{/sha}',
   'git_tags_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/tags{/sha}',
   'git_refs_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/refs{/sha}',
   'trees_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/trees{/sha}',
   'statuses_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/statuses/{sha}',
   'languages_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/languages',
   'stargazers_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/stargazers',
   'contributors_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/contributors',
   'subscribers_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/subscribers',
   'subscription_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/subscription',
   'commits_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/commits{/sha}',
   'git_commits_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/commits{/sha}',
   'comments_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/comments{/number}',
   'issue_comment_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues/comments{/number}',
   'contents_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/contents/{+path}',
   'compare_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/compare/{base}...{head}',
   'merges_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/merges',
   'archive_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/{archive_format}{/ref}',
   'downloads_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/downloads',
   'issues_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues{/number}',
   'pulls_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/pulls{/number}',
   'milestones_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/milestones{/number}',
   'notifications_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/notifications{?since,all,participating}',
   'labels_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/labels{/name}',
   'releases_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/releases{/id}',
   'deployments_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/deployments',
   'created_at': '2022-05-16T19:49:03Z',
   'updated_at': '2026-03-08T14:21:57Z',
   'pushed_at': '2025-03-25T21:20:38Z',
   'git_url': 'git://github.com/amzn/ads-advanced-tools-docs.git',
   'ssh_url': 'git@github.com:amzn/ads-advanced-tools-docs.git',
   'clone_url': 'https://github.com/amzn/ads-advanced-tools-docs.git',
   'svn_url': 'https://github.com/amzn/ads-advanced-tools-docs',
   'homepage': 'https://advertising.amazon.com/API/docs/en-us/index',
   'size': 719,
   'stargazers_count': 137,
   'watchers_count': 137,
   'language': 'Jupyter Notebook',
   'has_issues': True,
   'has_projects': False,
   'has_downloads': True,
   'has_wiki': False,
   'has_pages': False,
   'has_discussions': True,
   'forks_count': 42,
   'mirror_url': None,
   'archived': False,
   'disabled': False,
   'open_issues_count': 49,
   'license': {'key': 'mit-0',
    'name': 'MIT No Attribution',
    'spdx_id': 'MIT-0',
    'url': 'https://api.github.com/licenses/mit-0',
    'node_id': 'MDc6TGljZW5zZTQx'},
   'allow_forking': True,
   'is_template': False,
   'web_commit_signoff_required': False,
   'has_pull_requests': True,
   'pull_request_creation_policy': 'all',
   'topics': ['amazon', 'amazon-ads-api', 'amazon-marketing-stream'],
   'visibility': 'public',
   'forks': 42,
   'open_issues': 49,
   'watchers': 137,
   'default_branch': 'main',
   'permissions': {'admin': False,
    'maintain': False,
    'push': False,
    'triage': False,
    'pull': True}},
  {'id': 958141729,
   'node_id': 'R_kgDOORwVIQ',
   'name': 'ads-pao-amznjs-gtm-server-side-template',
   'full_name': 'amzn/ads-pao-amznjs-gtm-server-side-template',
   'private': False,
   'owner': {'login': 'amzn',
    'id': 8594673,
    'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
    'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/amzn',
    'html_url': 'https://github.com/amzn',
    'followers_url': 'https://api.github.com/users/amzn/followers',
    'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
    'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
    'organizations_url': 'https://api.github.com/users/amzn/orgs',
    'repos_url': 'https://api.github.com/users/amzn/repos',
    'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/amzn/received_events',
    'type': 'Organization',
    'user_view_type': 'public',
    'site_admin': False},
   'html_url': 'https://github.com/amzn/ads-pao-amznjs-gtm-server-side-template',
   'description': None,
   'fork': False,
   'url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template',
   'forks_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/forks',
   'keys_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/keys{/key_id}',
   'collaborators_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/collaborators{/collaborator}',
   'teams_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/teams',
   'hooks_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/hooks',
   'issue_events_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/issues/events{/number}',
   'events_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/events',
   'assignees_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/assignees{/user}',
   'branches_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/branches{/branch}',
   'tags_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/tags',
   'blobs_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/git/blobs{/sha}',
   'git_tags_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/git/tags{/sha}',
   'git_refs_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/git/refs{/sha}',
   'trees_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/git/trees{/sha}',
   'statuses_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/statuses/{sha}',
   'languages_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/languages',
   'stargazers_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/stargazers',
   'contributors_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/contributors',
   'subscribers_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/subscribers',
   'subscription_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/subscription',
   'commits_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/commits{/sha}',
   'git_commits_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/git/commits{/sha}',
   'comments_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/comments{/number}',
   'issue_comment_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/issues/comments{/number}',
   'contents_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/contents/{+path}',
   'compare_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/compare/{base}...{head}',
   'merges_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/merges',
   'archive_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/{archive_format}{/ref}',
   'downloads_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/downloads',
   'issues_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/issues{/number}',
   'pulls_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/pulls{/number}',
   'milestones_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/milestones{/number}',
   'notifications_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/notifications{?since,all,participating}',
   'labels_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/labels{/name}',
   'releases_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/releases{/id}',
   'deployments_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/deployments',
   'created_at': '2025-03-31T17:58:12Z',
   'updated_at': '2025-10-10T14:15:06Z',
   'pushed_at': '2025-08-26T19:03:24Z',
   'git_url': 'git://github.com/amzn/ads-pao-amznjs-gtm-server-side-template.git',
   'ssh_url': 'git@github.com:amzn/ads-pao-amznjs-gtm-server-side-template.git',
   'clone_url': 'https://github.com/amzn/ads-pao-amznjs-gtm-server-side-template.git',
   'svn_url': 'https://github.com/amzn/ads-pao-amznjs-gtm-server-side-template',
   'homepage': None,
   'size': 118,
   'stargazers_count': 2,
   'watchers_count': 2,
   'language': 'Smarty',
   'has_issues': True,
   'has_projects': True,
   'has_downloads': True,
   'has_wiki': True,
   'has_pages': False,
   'has_discussions': False,
   'forks_count': 2,
   'mirror_url': None,
   'archived': False,
   'disabled': False,
   'open_issues_count': 2,
   'license': {'key': 'apache-2.0',
    'name': 'Apache License 2.0',
    'spdx_id': 'Apache-2.0',
    'url': 'https://api.github.com/licenses/apache-2.0',
    'node_id': 'MDc6TGljZW5zZTI='},
   'allow_forking': True,
   'is_template': False,
   'web_commit_signoff_required': False,
   'has_pull_requests': True,
   'pull_request_creation_policy': 'all',
   'topics': [],
   'visibility': 'public',
   'forks': 2,
   'open_issues': 2,
   'watchers': 2,
   'default_branch': 'main',
   'permissions': {'admin': False,
    'maintain': False,
    'push': False,
    'triage': False,
    'pull': True}},
  {'id': 674005216,
   'node_id': 'R_kgDOKCyA4A',
   'name': 'ads-pao-amznjs-gtm-template',
   'full_name': 'amzn/ads-pao-amznjs-gtm-template',
   'private': False,
   'owner': {'login': 'amzn',
    'id': 8594673,
    'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
    'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/amzn',
    'html_url': 'https://github.com/amzn',
    'followers_url': 'https://api.github.com/users/amzn/followers',
    'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
    'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
    'organizations_url': 'https://api.github.com/users/amzn/orgs',
    'repos_url': 'https://api.github.com/users/amzn/repos',
    'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/amzn/received_events',
    'type': 'Organization',
    'user_view_type': 'public',
    'site_admin': False},
   'html_url': 'https://github.com/amzn/ads-pao-amznjs-gtm-template',
   'description': None,
   'fork': False,
   'url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-template',
   'forks_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-template/forks',

In [25]:
len(repos_list)

5

In [26]:
len(repos_list[0])

30

In [27]:
repos_list[0]

[{'id': 171339259,
  'node_id': 'MDEwOlJlcG9zaXRvcnkxNzEzMzkyNTk=',
  'name': '.github',
  'full_name': 'amzn/.github',
  'private': False,
  'owner': {'login': 'amzn',
   'id': 8594673,
   'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/amzn',
   'html_url': 'https://github.com/amzn',
   'followers_url': 'https://api.github.com/users/amzn/followers',
   'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
   'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
   'organizations_url': 'https://api.github.com/users/amzn/orgs',
   'repos_url': 'https://api.github.com/users/amzn/repos',
   'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/amzn/received_events',
   'type': 'Organization',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/amzn/.github',
  'description': None,
  'fork': False,
  'url': 'https://api.github.com/repos/amzn/.github',
  'forks_url': 'https://api.github.com/repos/amzn/.github/forks',
  'keys_url': 'https://api.github.com/repos/amzn/.github/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/amzn/.github/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/amzn/.github/teams',
  'hooks_url': 'https://api.github.com/repos/amzn/.github/hooks',
  'issue_events_url': 'https://api.github.com/repos/amzn/.github/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/amzn/.github/events',
  'assignees_url': 'https://api.github.com/repos/amzn/.github/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/amzn/.github/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/amzn/.github/tags',
  'blobs_url': 'https://api.github.com/repos/amzn/.github/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/amzn/.github/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/amzn/.github/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/amzn/.github/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/amzn/.github/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/amzn/.github/languages',
  'stargazers_url': 'https://api.github.com/repos/amzn/.github/stargazers',
  'contributors_url': 'https://api.github.com/repos/amzn/.github/contributors',
  'subscribers_url': 'https://api.github.com/repos/amzn/.github/subscribers',
  'subscription_url': 'https://api.github.com/repos/amzn/.github/subscription',
  'commits_url': 'https://api.github.com/repos/amzn/.github/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/amzn/.github/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/amzn/.github/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/amzn/.github/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/amzn/.github/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/amzn/.github/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/amzn/.github/merges',
  'archive_url': 'https://api.github.com/repos/amzn/.github/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/amzn/.github/downloads',
  'issues_url': 'https://api.github.com/repos/amzn/.github/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/amzn/.github/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/amzn/.github/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/amzn/.github/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/amzn/.github/labels{/name}',
  'releases_url': 'https://api.github.com/repos/amzn/.github/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/amzn/.github/deployments',
  'created_at': '2019-02-18T18:59:22Z',
  'updated_at': '2026-01-12T04:08:52Z',
  'pushed_at': '2024-10-18T22:23:05Z',
  'git_url': 'git://github.com/amzn/.github.git',
  'ssh_url': 'git@github.com:amzn/.github.git',
  'clone_url': 'https://github.com/amzn/.github.git',
  'svn_url': 'https://github.com/amzn/.github',
  'homepage': None,
  'size': 24,
  'stargazers_count': 20,
  'watchers_count': 20,
  'language': None,
  'has_issues': True,
  'has_projects': False,
  'has_downloads': True,
  'has_wiki': False,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 439,
  'mirror_url': None,
  'archived': False,
  'disabled': False,
  'open_issues_count': 3,
  'license': None,
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'has_pull_requests': True,
  'pull_request_creation_policy': 'all',
  'topics': [],
  'visibility': 'public',
  'forks': 439,
  'open_issues': 3,
  'watchers': 20,
  'default_branch': 'master',
  'permissions': {'admin': False,
   'maintain': False,
   'push': False,
   'triage': False,
   'pull': True}},
 {'id': 492978607,
  'node_id': 'R_kgDOHWJBrw',
  'name': 'ads-advanced-tools-docs',
  'full_name': 'amzn/ads-advanced-tools-docs',
  'private': False,
  'owner': {'login': 'amzn',
   'id': 8594673,
   'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/amzn',
   'html_url': 'https://github.com/amzn',
   'followers_url': 'https://api.github.com/users/amzn/followers',
   'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
   'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
   'organizations_url': 'https://api.github.com/users/amzn/orgs',
   'repos_url': 'https://api.github.com/users/amzn/repos',
   'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/amzn/received_events',
   'type': 'Organization',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/amzn/ads-advanced-tools-docs',
  'description': 'Code samples and supplements for the Amazon Ads advanced tools center',
  'fork': False,
  'url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs',
  'forks_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/forks',
  'keys_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/teams',
  'hooks_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/hooks',
  'issue_events_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/events',
  'assignees_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/tags',
  'blobs_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/languages',
  'stargazers_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/stargazers',
  'contributors_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/contributors',
  'subscribers_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/subscribers',
  'subscription_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/subscription',
  'commits_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/merges',
  'archive_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/downloads',
  'issues_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/labels{/name}',
  'releases_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/deployments',
  'created_at': '2022-05-16T19:49:03Z',
  'updated_at': '2026-03-08T14:21:57Z',
  'pushed_at': '2025-03-25T21:20:38Z',
  'git_url': 'git://github.com/amzn/ads-advanced-tools-docs.git',
  'ssh_url': 'git@github.com:amzn/ads-advanced-tools-docs.git',
  'clone_url': 'https://github.com/amzn/ads-advanced-tools-docs.git',
  'svn_url': 'https://github.com/amzn/ads-advanced-tools-docs',
  'homepage': 'https://advertising.amazon.com/API/docs/en-us/index',
  'size': 719,
  'stargazers_count': 137,
  'watchers_count': 137,
  'language': 'Jupyter Notebook',
  'has_issues': True,
  'has_projects': False,
  'has_downloads': True,
  'has_wiki': False,
  'has_pages': False,
  'has_discussions': True,
  'forks_count': 42,
  'mirror_url': None,
  'archived': False,
  'disabled': False,
  'open_issues_count': 49,
  'license': {'key': 'mit-0',
   'name': 'MIT No Attribution',
   'spdx_id': 'MIT-0',
   'url': 'https://api.github.com/licenses/mit-0',
   'node_id': 'MDc6TGljZW5zZTQx'},
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'has_pull_requests': True,
  'pull_request_creation_policy': 'all',
  'topics': ['amazon', 'amazon-ads-api', 'amazon-marketing-stream'],
  'visibility': 'public',
  'forks': 42,
  'open_issues': 49,
  'watchers': 137,
  'default_branch': 'main',
  'permissions': {'admin': False,
   'maintain': False,
   'push': False,
   'triage': False,
   'pull': True}},
 {'id': 958141729,
  'node_id': 'R_kgDOORwVIQ',
  'name': 'ads-pao-amznjs-gtm-server-side-template',
  'full_name': 'amzn/ads-pao-amznjs-gtm-server-side-template',
  'private': False,
  'owner': {'login': 'amzn',
   'id': 8594673,
   'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/amzn',
   'html_url': 'https://github.com/amzn',
   'followers_url': 'https://api.github.com/users/amzn/followers',
   'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
   'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
   'organizations_url': 'https://api.github.com/users/amzn/orgs',
   'repos_url': 'https://api.github.com/users/amzn/repos',
   'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/amzn/received_events',
   'type': 'Organization',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/amzn/ads-pao-amznjs-gtm-server-side-template',
  'description': None,
  'fork': False,
  'url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template',
  'forks_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/forks',
  'keys_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/teams',
  'hooks_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/hooks',
  'issue_events_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/events',
  'assignees_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/tags',
  'blobs_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/languages',
  'stargazers_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/stargazers',
  'contributors_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/contributors',
  'subscribers_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/subscribers',
  'subscription_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/subscription',
  'commits_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/merges',
  'archive_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/downloads',
  'issues_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/labels{/name}',
  'releases_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-server-side-template/deployments',
  'created_at': '2025-03-31T17:58:12Z',
  'updated_at': '2025-10-10T14:15:06Z',
  'pushed_at': '2025-08-26T19:03:24Z',
  'git_url': 'git://github.com/amzn/ads-pao-amznjs-gtm-server-side-template.git',
  'ssh_url': 'git@github.com:amzn/ads-pao-amznjs-gtm-server-side-template.git',
  'clone_url': 'https://github.com/amzn/ads-pao-amznjs-gtm-server-side-template.git',
  'svn_url': 'https://github.com/amzn/ads-pao-amznjs-gtm-server-side-template',
  'homepage': None,
  'size': 118,
  'stargazers_count': 2,
  'watchers_count': 2,
  'language': 'Smarty',
  'has_issues': True,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': True,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 2,
  'mirror_url': None,
  'archived': False,
  'disabled': False,
  'open_issues_count': 2,
  'license': {'key': 'apache-2.0',
   'name': 'Apache License 2.0',
   'spdx_id': 'Apache-2.0',
   'url': 'https://api.github.com/licenses/apache-2.0',
   'node_id': 'MDc6TGljZW5zZTI='},
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'has_pull_requests': True,
  'pull_request_creation_policy': 'all',
  'topics': [],
  'visibility': 'public',
  'forks': 2,
  'open_issues': 2,
  'watchers': 2,
  'default_branch': 'main',
  'permissions': {'admin': False,
   'maintain': False,
   'push': False,
   'triage': False,
   'pull': True}},
 {'id': 674005216,
  'node_id': 'R_kgDOKCyA4A',
  'name': 'ads-pao-amznjs-gtm-template',
  'full_name': 'amzn/ads-pao-amznjs-gtm-template',
  'private': False,
  'owner': {'login': 'amzn',
   'id': 8594673,
   'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/amzn',
   'html_url': 'https://github.com/amzn',
   'followers_url': 'https://api.github.com/users/amzn/followers',
   'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
   'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
   'organizations_url': 'https://api.github.com/users/amzn/orgs',
   'repos_url': 'https://api.github.com/users/amzn/repos',
   'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/amzn/received_events',
   'type': 'Organization',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/amzn/ads-pao-amznjs-gtm-template',
  'description': None,
  'fork': False,
  'url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-template',
  'forks_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-template/forks',
  'keys_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-template/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-template/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/amzn/ads-pao-amznjs-gtm-template/teams',

In [28]:
repos_list[0][10]

{'id': 225431811,
 'node_id': 'MDEwOlJlcG9zaXRvcnkyMjU0MzE4MTE=',
 'name': 'amazon-hub-counter-api-docs',
 'full_name': 'amzn/amazon-hub-counter-api-docs',
 'private': False,
 'owner': {'login': 'amzn',
  'id': 8594673,
  'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/amzn',
  'html_url': 'https://github.com/amzn',
  'followers_url': 'https://api.github.com/users/amzn/followers',
  'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
  'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
  'organizations_url': 'https://api.github.com/users/amzn/orgs',
  'repos_url': 'https://api.github.com/users/amzn/repos',
  'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/amzn/received_events',
  'type': 'Organization',
  'user_view_type': 'public',
  'site_admin': False},
 'html_url': 'https://github.com/amzn/amazon-hub-counter-api-docs',
 'description': None,
 'fork': False,
 'url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs',
 'forks_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/forks',
 'keys_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/keys{/key_id}',
 'collaborators_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/collaborators{/collaborator}',
 'teams_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/teams',
 'hooks_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/hooks',
 'issue_events_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/issues/events{/number}',
 'events_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/events',
 'assignees_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/assignees{/user}',
 'branches_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/branches{/branch}',
 'tags_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/tags',
 'blobs_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/git/blobs{/sha}',
 'git_tags_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/git/tags{/sha}',
 'git_refs_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/git/refs{/sha}',
 'trees_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/git/trees{/sha}',
 'statuses_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/statuses/{sha}',
 'languages_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/languages',
 'stargazers_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/stargazers',
 'contributors_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/contributors',
 'subscribers_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/subscribers',
 'subscription_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/subscription',
 'commits_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/commits{/sha}',
 'git_commits_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/git/commits{/sha}',
 'comments_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/comments{/number}',
 'issue_comment_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/issues/comments{/number}',
 'contents_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/contents/{+path}',
 'compare_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/compare/{base}...{head}',
 'merges_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/merges',
 'archive_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/{archive_format}{/ref}',
 'downloads_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/downloads',
 'issues_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/issues{/number}',
 'pulls_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/pulls{/number}',
 'milestones_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/milestones{/number}',
 'notifications_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/notifications{?since,all,participating}',
 'labels_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/labels{/name}',
 'releases_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/releases{/id}',
 'deployments_url': 'https://api.github.com/repos/amzn/amazon-hub-counter-api-docs/deployments',
 'created_at': '2019-12-02T17:30:48Z',
 'updated_at': '2025-11-14T14:10:16Z',
 'pushed_at': '2025-11-14T14:25:15Z',
 'git_url': 'git://github.com/amzn/amazon-hub-counter-api-docs.git',
 'ssh_url': 'git@github.com:amzn/amazon-hub-counter-api-docs.git',
 'clone_url': 'https://github.com/amzn/amazon-hub-counter-api-docs.git',
 'svn_url': 'https://github.com/amzn/amazon-hub-counter-api-docs',
 'homepage': None,
 'size': 3137,
 'stargazers_count': 6,
 'watchers_count': 6,
 'language': 'CSS',
 'has_issues': True,
 'has_projects': True,
 'has_downloads': True,
 'has_wiki': True,
 'has_pages': True,
 'has_discussions': False,
 'forks_count': 11,
 'mirror_url': None,
 'archived': False,
 'disabled': False,
 'open_issues_count': 2,
 'license': {'key': 'other',
  'name': 'Other',
  'spdx_id': 'NOASSERTION',
  'url': None,
  'node_id': 'MDc6TGljZW5zZTA='},
 'allow_forking': True,
 'is_template': False,
 'web_commit_signoff_required': False,
 'has_pull_requests': True,
 'pull_request_creation_policy': 'all',
 'topics': [],
 'visibility': 'public',
 'forks': 11,
 'open_issues': 2,
 'watchers': 6,
 'default_branch': 'master',
 'permissions': {'admin': False,
  'maintain': False,
  'push': False,
  'triage': False,
  'pull': True}}

In [29]:
# DESAFIO 2 - Faça uma requisição pegando os seguidores de um usuário do GitHub
username = 'amzn'
url = f'https://api.github.com/users/{username}/followers'
headers = {
    'X-GitHub-Api-Version': '2022-11-28',
    'Authorization': 'Bearer ' + accesss_token
}

response = requests.get(url, headers=headers)
followers = response.json()

In [30]:
followers_list = []
i = 1

while True:
    url_page = f'{url}?page={i}'
    response = requests.get(url_page, headers=headers)

    if len(response.json()) == 0:
       break
    followers_list.append(response.json())
    i += 1
    print(len(response.json()))

30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
25

In [31]:
repos_list[0][2]['name']

'ads-pao-amznjs-gtm-server-side-template'

In [32]:
repos_name = []

for page in repos_list:
    for repo in page:
        repos_name.append(repo['name'])

In [33]:
repos_name[:10]

['.github',
 'ads-advanced-tools-docs',
 'ads-pao-amznjs-gtm-server-side-template',
 'ads-pao-amznjs-gtm-template',
 'alexa-coho',
 'alexa-skills-kit-js',
 'amazon-ads-advertiser-audience-normalization-sdk-py',
 'amazon-advertising-api-php-sdk',
 'amazon-codeguru-profiler-for-spark',
 'amazon-frustration-free-setup-certification-tool']

In [34]:
len(repos_name)

150

In [35]:
repos_list[1][1]['language']

'PHP'

In [36]:
repos_language = []

for page in repos_list:
    for repo in page:
        #if repo['language'] is not None:
          repos_language.append(repo['language'])

repos_language[:10]

[None,
 'Jupyter Notebook',
 'Smarty',
 'Smarty',
 'JavaScript',
 None,
 'Python',
 'PHP',
 'Java',
 'Python']

In [37]:
import pandas as pd

In [38]:
dados_amz = pd.DataFrame()
dados_amz['repository_name'] = repos_name
dados_amz['language'] = repos_language

In [39]:
dados_amz

                             repository_name          language
0                                    .github              None
1                    ads-advanced-tools-docs  Jupyter Notebook
2    ads-pao-amznjs-gtm-server-side-template            Smarty
3                ads-pao-amznjs-gtm-template            Smarty
4                                 alexa-coho        JavaScript
..                                       ...               ...
145                          smoke-framework             Swift
146     smoke-framework-application-generate             Swift
147                 smoke-framework-examples             Swift
148                               smoke-http             Swift
149                             sparse-vqvae            Python

[150 rows x 2 columns]

In [40]:
dados_amz.to_csv('amazon.csv', index=True)

In [41]:
# Desafio 3 - Gere um arquivo CSV com os nomes dos seguidores do Github
followers_names = []

for page in followers_list:
    for repo in page:
        followers_names.append(repo['login'])

len(followers_names)

2515

In [42]:
seguidores_amzn = pd.DataFrame({'nome': followers_names})
seguidores_amzn

                  nome
0              tkersey
1             njonsson
2            bangpound
3           vincentkoc
4                Rud5G
...                ...
2510        richi-reds
2511          villagga
2512        quanphoton
2513          yulinlyl
2514  charlotte-otoole

[2515 rows x 1 columns]

In [43]:
seguidores_amzn.to_csv('seguidores.csv', index=True, index_label='id')

In [44]:
api_base_url = 'https://api.github.com'
url = f'{api_base_url}/user/repos'

headers

{'X-GitHub-Api-Version': '2022-11-28',
 'Authorization': 'Bearer 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'}

In [ ]:
data = {
    'name' : 'linguagens-utilizadas',
    'description' : 'Repositório para armazenar as linguagens utilizadas nos repositórios da Amazon',
    'private' : False
}

reposta = requests.post(url, headers=headers, json=data)
reposta.status_code

200

In [48]:
import base64

In [50]:
# Envio do arquivo amazon para o repositório do github
with open('amazon.csv', 'rb') as file:
    file_content = file.read()

encoded_content = base64.b64encode(file_content).decode('utf-8')
api_base_url = 'https://api.github.com'
username = 'rdzvergara'
repo = 'linguagens-utilizadas'
file_path = 'amazon.csv'

url = f'{api_base_url}/repos/{username}/{repo}/contents/{file_path}'
headers = {
    'X-GitHub-Api-Version': '2022-11-28',
    'Authorization': 'Bearer ' + accesss_token
}

data = {
    'message' : 'Adicionando o arquivo amazon.csv',
    'content' : encoded_content
}

response = requests.put(url, headers=headers, json=data)
response.status_code

201

In [51]:
# Envio do arquivo seguidores para o repositório do github
with open('seguidores.csv', 'rb') as file:
    file_content = file.read()

encoded_content = base64.b64encode(file_content).decode('utf-8')
api_base_url = 'https://api.github.com'
username = 'rdzvergara'
repo = 'linguagens-utilizadas'
file_path = 'seguidores.csv'

url = f'{api_base_url}/repos/{username}/{repo}/contents/{file_path}'
headers = {
    'X-GitHub-Api-Version': '2022-11-28',
    'Authorization': 'Bearer ' + accesss_token
}

data = {
    'message' : 'Adicionando o arquivo seguidores.csv',
    'content' : encoded_content
}

response = requests.put(url, headers=headers, json=data)
response.status_code

201

In [53]:

api_base_url = 'https://api.github.com'
username = 'amzn'
repo = 'app-platform'
file_path = 'seguidores.csv'

url = f'{api_base_url}/repos/{username}/{repo}/forks'
headers = {
    'Accept' : 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Authorization': 'Bearer ' + accesss_token
}
data = {
    'name' : 'fork-amazon',
    'default_branch_only' : True
}

reposta = requests.post(url, headers=headers, json=data)
reposta.status_code

202